version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app  # Mapeamento do diretório do projeto no host para o diretório de trabalho no contêiner
    ports:
      - "3000:3000"